export const routeName = {
    Welcome: 'Welcome',
    Home: 'Home',
    Signin: 'Signin',
    Signup: 'Signup',
    ForgotPassword: 'ForgotPassword',
    Subdistrict: 'Subdistrict',
    PopulationM: 'PopulationM',
    PopulationF: 'PopulationF',
    Religion: 'Religion',
    School: 'School',
    LocalOrganization: 'LocalOrganization',
    YouthNetwork: 'YouthNetwork',
    LocalMaps: 'LocalMaps',
    LocalCalendar: 'LocalCalendar',
    UserList: 'UserList',
    Profile: 'Profile',
    ProfileEdit: 'ProfileEdit',
    AY: 'AY',
    Dashboard: 'Dashboard',
    DashboardGust: 'DashboardGust',
    GuestHome: 'GuestHome',
    LocalDisease: 'LocalDisease'

}